### ISSUE TITLE
I get a error

### ISSUE THREAD

**Issue by carlding1990** [element-plus/vue-cli-plugin-element-plus#11]
``` powershell
PS D:\Temp\VSCode\0-dimension-dictionary> vue add element-plus
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing vue-cli-plugin-element-plus...


added 1 package in 2s

1 package is looking for funding
  run `npm fund` for details
✔  Successfully installed plugin: vue-cli-plugin-element-plus

? How do you want to import Element Plus? Fully import
? Do you want to overwrite the SCSS variables of Element Plus? Yes
? Choose the locale you want to load, the default locale is English (en) zh-cn

🚀  Invoking generator for vue-cli-plugin-element-plus...
📦  Installing additional dependencies...


added 8 packages in 3s

1 package is looking for funding
  run `npm fund` for details
⚓  Running completion hooks...
 ERROR  TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at D:\Temp\VSCode\0-dimension-dictionary\node_modules\vue-cli-plugin-element-plus\generator\index.js:45:45
    at runGenerator (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async invoke (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)
PS D:\Temp\VSCode\0-dimension-dictionary>
```

**Comment by watonyweng** [comment]
Duplicate of #6

**Comment by duola8789** [comment]
+1

**Comment by kid1412621** [comment]
+1

**Comment by przemekk1385** [comment]
+1

**Comment by dskin** [comment]
+1 三月份的问题到现在都没解决过的吗。。。

**Comment by lorenzo-dallamuta** [comment]
+1 this is a typescript issue (see #18 to see what happens if you ignore this issue and run the project). I guess this plugin doesn't support typescript, not sure if it ever will

**Comment by patrpok** [comment]
This issue is already mentioned [here](https://github.com/element-plus/vue-cli-plugin-element-plus/issues/6#issuecomment-799971720).
If using Vue CLI, possible workaround is to go through "Manually select features" when creating vue project and then either **unselect Linter / formatter**, otherwise keep it selected but in the next step of installation select **ESlint with error prevention only.** Seems that other installation options have no effect on this error and thus may be used at discretion.
