### ISSUE TITLE
Cannot read property 'replace' of undefined [bug fix]

### ISSUE THREAD

**Issue by tnnevol** [element-plus/vue-cli-plugin-element-plus#12]
不知道是不是官方小伙独爱单引号, 麻烦修改一下正则吧
```javascript
// ./node_modules/vue-cli-plugin-element-plus/generator/index.js:45:45 bug fix
// edit line 41
// error code
    const renderIndex = lines.findIndex(line => line.match(/createApp\(App\)(\.use\(\w*\))*\.mount\('#app'\)/))
// fix code
    const renderIndex = lines.findIndex(line => line.match(/createApp\(App\)(\.use\(\w*\))*\.mount\(['"]#app['"]\)/))
```

**Comment by CoolersCoder** [comment]
I get same issue , 同样的问题+1.

**Comment by HeliumTang** [comment]
只能等官方修bug了吗？

**Comment by saltfishh** [comment]
> 不知道是不是官方小伙独爱单引号, 麻烦修改一下正则吧
> 
> ```js
> // ./node_modules/vue-cli-plugin-element-plus/generator/index.js:45:45 bug fix
> // edit line 41
> // error code
>     const renderIndex = lines.findIndex(line => line.match(/createApp\(App\)(\.use\(\w*\))*\.mount\('#app'\)/))
> // fix code
>     const renderIndex = lines.findIndex(line => line.match(/createApp\(App\)(\.use\(\w*\))*\.mount\(['"]#app['"]\)/))
> ```

似乎还是报错

**Comment by pollux2015** [comment]
遇到同样问题

**Comment by LittleSound** [comment]
这个正则还要求匹配 createApp，如果 createApp 在另外一行就不行了
![image](https://user-images.githubusercontent.com/19204772/114356180-e55cbf00-9ba2-11eb-94c4-82835f30ca3b.png)

**Comment by jdinartejesus** [comment]
Can someone create a PR?

**Comment by dmytropryshliak** [comment]
Does anybody know why is it not merged yet?

**Comment by censujiang** [comment]
我也遇到相同的问题了
` ERROR  TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at D:\git\sailoudcodegit\unidownpage\node_modules\vue-cli-plugin-element-plus\generator\index.js:45:45
    at runGenerator (C:\Users\censujiang\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async invoke (C:\Users\censujiang\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)`
