### ISSUE TITLE
vue add element-plus commond throw an error

### ISSUE THREAD

**Issue by code1379** [element-plus/vue-cli-plugin-element-plus#21]
ERROR  TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at D:\testProject\element-demo\node_modules\vue-cli-plugin-element-plus\generator\index.js:45:45
    at runGenerator (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async invoke (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)

**Window 10 platform has this problem**, Mac OS is fine

**Comment by ghost** [comment]
i get a same error
system is centos 7.9

**Comment by ghost** [comment]
ERROR  TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at /www/wwwroot/aip.chinaydfx.com/node_modules/vue-cli-plugin-element-plus/generator/index.js:45:45
    at runGenerator (/opt/nvm/versions/node/v14.17.4/lib/node_modules/@vue/cli/lib/invoke.js:132:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async invoke (/opt/nvm/versions/node/v14.17.4/lib/node_modules/@vue/cli/lib/invoke.js:92:3)

**Comment by gamecss** [comment]
i think this has something to vue-router

**Comment by gamecss** [comment]
@zazzaz

**Comment by ghost** [comment]
@code1379 
use ESLint with error prevention only

**Comment by ghost** [comment]
i tested options, found result:
ESLint + Prettier --> Error
ESLint with error prevention only --> Success
other not tested

**Comment by MinWest** [comment]
i get a same error

vue -V
@vue/cli 4.5.15

node -v
v16.13.1

npm -v
8.3.0

**Comment by YunYouJun** [comment]
Sorry, I think this plug-in may no longer be maintained. Considering that element has been updated a lot, you can take a look at this https://github.com/element-plus/unplugin-element-plus/ .
